### ISSUE TITLE
java.lang.ExceptionInInitializerError: unable to load from [paddle_inference.dll]

### ISSUE THREAD

**Issue by xuxh6** [jiangnanboy/java-springboot-paddleocr-v2#2]
不能加载这个文件，文件已经按照说明都放在了指定的位置。

Caused by: java.lang.ExceptionInInitializerError: unable to load from [paddle_inference.dll]
	at io.github.greycode.JniLoader.load(JniLoader.java:53) ~[ocrlite-3.0.0.jar:na]
	at io.github.greycode.PaddleOcr.loadLib(PaddleOcr.java:171) ~[ocrlite-3.0.0.jar:na]
	at io.github.greycode.PaddleOcr.<init>(PaddleOcr.java:133) ~[ocrlite-3.0.0.jar:na]
	at com.sy.ocr.OcrService.loadOcrDriver(OcrService.java:69) ~[classes/:1.0-SNAPSHOT]
	at com.sy.ocr.OcrService.init(OcrService.java:40) ~[classes/:1.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.16.jar:5.3.16]

报错位置显示是
![image](https://github.com/jiangnanboy/java-springboot-paddleocr-v2/assets/18001416/c83d7b2e-4f7d-483b-9ea8-2651a6c38440)
PaddleOcr.java这个文件加载时报的错误。我尝试更新版本到3.0.2 但是依然报错。

**Comment by zch0214** [comment]
我也碰到了，这问题解决了吗？

**Comment by xuxh6** [comment]
> 
没有解决

**Comment by xuxh6** [comment]
> 我也碰到了，这问题解决了吗？

应该就是paddle_inference.dll文件错误

**Comment by hongwazi** [comment]
这玩意是不是很吃内存啊，在我电脑上能启动，识别的时候内存就不够用了。
